export const data = {
  questions: [
    {
      q: 'Bạn cảm thấy hứng thú nhất với ngôn ngữ lập trình nào sau đây?',
      a: {
        Java: {
          1: 2,
          3: 4,
          4: 2,
          5: 2,
          6: 2,
          7: 3,
          8: 4,
          9: 3,
          10: 2,
          11: 2,
          12: 1,
          13: 1,
        },
        Javascript: {
          1: 4,
          2: 2,
          3: 2,
          4: 2,
          6: 1,
          7: 2,
          8: 2,
          9: 4,
          10: 2,
          11: 4,
          12: 1,
        },
        'HTML/CSS': {
          1: 4,
          2: 3,
          4: 1,
          7: 2,
          8: 2,
          9: 1,
          11: 1,
          12: 1,
          14: 2,
        },
        'C#': {
          4: 2,
          7: 4,
          8: 4,
          10: 1,
          12: 1,
        },
      },
    },

    {
      q: 'Bạn cảm thấy hứng thú nhất với ngôn ngữ lập trình nào sau đây?',
      a: {
        Python: {
          1: 1,
          3: 3,
          4: 2,
          5: 4,
          6: 3,
          7: 2,
          8: 1,
          10: 2,
          12: 1,
          13: 4,
        },
        Javascript: {
          1: 4,
          2: 2,
          3: 2,
          4: 2,
          6: 1,
          7: 2,
          8: 2,
          9: 4,
          10: 2,
          11: 4,
          12: 1,
        },
        'HTML/CSS': {
          1: 4,
          2: 3,
          4: 1,
          7: 2,
          8: 2,
          9: 1,
          11: 1,
          12: 1,
          14: 2,
        },
        'C#': {
          4: 2,
          7: 4,
          8: 4,
          10: 1,
          12: 1,
        },
      },
    },

    {
      q: 'Trong quá trình học tập, bạn thấy ngôn ngữ nào dễ học và học nhanh nhất?',
      a: {
        'Các ngôn ngữ lập trình hướng đối tượng như C, C++, Java, C#': {
          1: 1,
          3: 1,
          4: 1,
          7: 1,
          8: 1,
          10: 1,
          11: 1,
          12: 1,
        },
        'Các ngôn ngữ có cấu trúc đơn giản, dễ đọc như Python, Javascript': {
          1: 1,
          2: 1,
          3: 1,
          4: 1,
          5: 1,
          6: 1,
          7: 1,
          9: 1,
          10: 1,
          12: 1,
          13: 1,
        },
        'Các siêu văn bản như HTML và CSS': {
          1: 1,
          2: 1,
          4: 1,
          7: 1,
          8: 1,
          9: 1,
          11: 1,
          12: 1,
          14: 1,
        },
        'Cảm thấy bản thân không có năng khiếu nhiều trong lập trình, ngôn ngữ nào học cũng khá vất vả':
          {
            4: 1,
            14: 1,
          },
      },
    },

    {
      q: 'Bạn cảm thấy có hứng thú với?',
      a: {
        'Giao diện của các trang web, phần mềm': {
          1: 1,
          2: 3,
          7: 1,
          8: 1,
          14: 4,
        },
        'Các đoạn code chạy phía sau các trang web, chương trình': {
          1: 2,
          2: 1,
          4: 2,
          7: 2,
          8: 3,
          10: 1,
          11: 3,
          12: 3,
          13: 1,
        },
        'Các mối liên hệ giữa các hệ thống máy tính và không gian mạng': {
          1: 1,
          3: 3,
          8: 1,
          9: 3,
          11: 2,
        },
        'Các nguồn dữ liệu và tập hợp dữ liệu mà các trang web và phần mềm xử lý':
          {
            1: 1,
            3: 2,
            5: 3,
            6: 3,
            8: 1,
            9: 2,
            10: 3,
            11: 1,
          },
      },
    },

    {
      q: 'Trong các nhóm công cụ sau đây, bạn đã từng sử dụng/biết đến ít nhất 1 công cụ trong nhóm công cụ nào?',
      a: {
        'SASS, PowerBI, Visio': {
          3: 1,
          4: 1,
          5: 3,
          6: 4,
          7: 1,
          8: 3,
          9: 1,
          10: 4,
          12: 2,
          14: 2,
        },
        'Adobe Premiere, Adobe Effect': {
          7: 1,
          14: 1,
        },
        'Paint.NET, Illustrator': {
          2: 1,
          7: 2,
          8: 1,
          12: 1,
          14: 3,
        },
        'Figma, Photoshop': {
          1: 2,
          2: 3,
          7: 2,
          8: 2,
          12: 1,
          14: 4,
        },
      },
    },

    {
      q: 'Bạn đã từng nghe tới/sử dụng loại cơ sở dữ liệu nào sau đây?',
      a: {
        'Cơ sở dữ liệu quan hệ (SQL)': {
          1: 1,
          3: 3,
          4: 1,
          5: 4,
          6: 4,
          7: 2,
          8: 1,
          9: 4,
          10: 4,
          11: 2,
          12: 1,
          13: 2,
        },
        'Cơ sở dữ liệu phi cấu trúc (NoSQL)': {
          1: 1,
          3: 3,
          4: 1,
          5: 4,
          6: 4,
          7: 2,
          8: 1,
          9: 4,
          10: 4,
          11: 2,
          12: 1,
          13: 2,
        },
        'Các loại cơ sở dữ liệu khác': {
          1: 2,
          2: 2,
          3: 2,
          4: 2,
          5: 3,
          6: 3,
          7: 2,
          8: 3,
          9: 2,
          10: 3,
          11: 2,
          12: 2,
          13: 2,
        },
        'Chưa biết gì về cơ sở dữ liệu/chưa dùng cơ sở dữ liệu bao giờ': {
          2: 3,
          14: 3,
        },
      },
    },

    {
      q: 'Sau khi ra trường, bạn có mong muốn được làm việc ở?',
      a: {
        'Các cơ quan trực thuộc Chính phủ, Quân đội': {
          1: 1,
          2: 1,
          3: 3,
          4: 1,
          5: 3,
          6: 3,
          8: 3,
          9: 1,
          10: 2,
          11: 2,
        },
        'Các tổ chức/doanh nghiệp trẻ, khởi nghiệp có tiềm năng': {
          1: 3,
          2: 3,
          3: 3,
          4: 3,
          7: 3,
          8: 3,
          9: 3,
          10: 3,
          11: 3,
          12: 3,
          14: 3,
        },
        'Các công ty liên quan đến truyền thông đa phương tiện': {
          1: 4,
          2: 4,
          5: 2,
          6: 2,
          11: 2,
          14: 4,
        },
        'Các công ty/doanh nghiệp lớn, nước ngoài': {
          3: 3,
          5: 3,
          6: 3,
          9: 3,
          10: 3,
          11: 3,
          12: 3,
          13: 3,
          14: 3,
        },
      },
    },

    {
      q: 'Trong các chứng chỉ nghiệp vụ sau đây, bạn có sức hút với chứng chỉ nào nhất? (Trong ngoặc là các chứng chỉ ví dụ)',
      a: {
        'Chứng chỉ bảo mật thông tin, kiểm soát hệ thống thông tin và rủi ro (CISSP - CRISC)':
          {
            1: 1,
            3: 5,
            4: 3,
            5: 3,
            8: 3,
            9: 4,
            10: 3,
            11: 2,
            12: 4,
          },
        'Chứng chỉ chuyên viên phân tích dữ liệu (Google Data Analytics Professional Certificate - IBM Data Analyst)':
          {
            3: 2,
            5: 5,
            6: 5,
            10: 4,
            11: 2,
            12: 2,
          },
        'Chứng chỉ thiết kế giao diện và bảo đảm trải nghiệm người dùng (Google UX Design Certificate)':
          {
            2: 4,
            7: 2,
            8: 2,
            12: 2,
            14: 5,
          },
        'Chứng chỉ kỹ sư phần mềm (Oracle Certified Professional)': {
          4: 3,
          8: 5,
          11: 3,
          12: 3,
        },
      },
    },

    {
      q: 'Trong các môn học sau, bạn cảm thấy hứng thú với?',
      a: {
        'Các môn liên quan đến toán học': {
          5: 3,
          6: 3,
          10: 3,
          13: 5,
        },
        'Các môn liên quan đến tư duy logic': {
          3: 4,
          5: 3,
          6: 3,
          10: 3,
          11: 2,
          12: 2,
          13: 3,
          14: 4,
        },
        'Các môn liên quan đến kỹ năng nghiệp vụ': {
          1: 3,
          2: 3,
          4: 3,
          7: 3,
          8: 3,
          9: 3,
          12: 3,
        },
        'Các môn liên quan đến con người và phục vụ con người': {
          12: 4,
          13: 4,
          14: 4,
        },
      },
    },

    {
      q: 'Mức lương bạn mong muốn sau này?',
      a: {
        '10 - 20 triệu/tháng': {
          2: 3,
          4: 3,
          11: 3,
          12: 3,
        },
        '20 - 30 triệu/tháng': {
          1: 3,
          6: 3,
          7: 3,
          10: 3,
          14: 3,
        },
        '30 - 40 triệu/tháng': {
          3: 3,
          5: 3,
          8: 3,
          9: 3,
        },
        'Trên 40 triệu/tháng': {
          13: 3,
        },
      },
    },
  ],
};
